name: demo
services:
    ingress:
        build: .
        domainname: docker.local
        ports:
            - 80:80
        restart: always
        depends_on:
          - backend
          - frontend

    frontend:
        build:
            context: elog-plus-frontend
            args:
                - API_ENDPOINT=/api/elogs/v1

    backend:
        build:
            context: elog-plus-backend
        ports:
            - 8080:8080
        environment:
            - ELOG_PLUS_MINIO_URL=http://minio:9000
            - ELOG_PLUS_MONGODB_URI=mongodb://elogs:elogs@mongodb-primary:27017/elogs?authSource=elogs
            - ELOG_PLUS_KAFKA_BOOTSTRAP=kafka:9092
            - WAIT_LOGGER_LEVEL=debug
            - WAIT_TIMEOUT=90
            - WAIT_HOSTS=mongodb-primary:27017, minio:9000
        depends_on:
        - mongodb-primary
        - minio
        - kafka